// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageDelivery.Data;

#nullable disable

namespace package_delivery_simulator.Migrations
{
    [DbContext(typeof(DeliveryDBContext))]
    [Migration("20260211083958_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PackageDelivery.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedDeliveries")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentLocationX")
                        .HasColumnType("REAL");

                    b.Property<double>("CurrentLocationY")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalDistanceTraveled")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("PackageDelivery.Models.DeliveryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedCourierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DestX")
                        .HasColumnType("REAL");

                    b.Property<double>("DestY")
                        .HasColumnType("REAL");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasDelayNotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCourierId");

                    b.HasIndex("Deadline");

                    b.HasIndex("Status");

                    b.HasIndex("ZoneId");

                    b.ToTable("DeliveryOrders");
                });

            modelBuilder.Entity("PackageDelivery.Models.RoutePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedTotalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptimizedOrderSequence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.ToTable("RoutePlans");
                });

            modelBuilder.Entity("PackageDelivery.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.HasIndex("Timestamp");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("PackageDelivery.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterY")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("PackageDelivery.Models.DeliveryOrder", b =>
                {
                    b.HasOne("PackageDelivery.Models.Courier", null)
                        .WithMany()
                        .HasForeignKey("AssignedCourierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PackageDelivery.Models.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PackageDelivery.Models.RoutePlan", b =>
                {
                    b.HasOne("PackageDelivery.Models.Courier", null)
                        .WithMany()
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackageDelivery.Models.StatusHistory", b =>
                {
                    b.HasOne("PackageDelivery.Models.DeliveryOrder", null)
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
